### ISSUE TITLE
Failed to load the find-letter package

### ISSUE THREAD

**Issue by eksortso** [tomkadwill/find-letter#7]
[Enter steps to reproduce:]

1. Installed the find-letter (0.2.0) package from Settings under Install
2. After installation, the error immediately occurred.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [find-letter](https://github.com/tomkadwill/find-letter) package 0.2.0

### Stack Trace

Failed to load the find-letter package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/find-letter/lib/find-letter-view.coffee:1:1)
    at /packages/find-letter/lib/find-letter-view.coffee:4:7
    at /packages/find-letter/lib/find-letter-view.coffee:69:11)
    at /packages/find-letter/lib/find-letter-view.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.17.2/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (C:/Users/Dave%20Ostrroske/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.17.2/resources/app/static/<embedded>:73:1)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:887:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:158:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:99:1)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:144:1)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:562:1)
    at PackageManager.module.exports.PackageManager.loadPackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:492:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:640:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-manager.js:519:1
    at exit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-manager.js:128:1)
    at triggerExitCallback (~/AppData/Local/atom/app-1.17.2/resources/app/src/buffered-process.js:338:1)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -2:47.6.0 core:select-all (input.hidden-input)
     -2:46.8.0 core:paste (input.hidden-input)
     -2:45 core:move-to-top (input.hidden-input)
     -2:42.3.0 editor:newline (input.hidden-input)
     -2:42.2.0 core:move-up (input.hidden-input)
     -2:33.5.0 core:backspace (input.hidden-input)
  2x -2:15.1.0 editor:move-to-beginning-of-word (input.hidden-input)
     -2:14.5.0 editor:move-to-end-of-word (input.hidden-input)
  2x -2:14.1.0 editor:select-to-beginning-of-word (input.hidden-input)
     -2:11.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:09.4.0 core:move-down (input.hidden-input)
     -2:09.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:08.7.0 editor:move-to-beginning-of-word (input.hidden-input)
     -2:08.2.0 core:backspace (input.hidden-input)
     -2:08.1.0 editor:newline (input.hidden-input)
  2x -1:48.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-clock 0.1.8 
atom-overtype-mode 0.3.4 
blame 0.12.0 
busy-signal 1.4.1 
convert-to-utf8 0.2.4 
ctrl-dir-scroll 0.2.3 
export-html 3.1.0 
file-bookmark 1.0.3 
find-letter 0.2.0 
highlight-selected 0.13.1 
insert-timestamp 0.2.4 
intentions 1.1.2 
iso8601-timestamp 0.1.1 
language-vba 0.2.5 
language-vbscript 0.9.0 
line-length-break 0.4.0 
linter 2.1.4 
linter-ui-default 1.6.0 
linter-xmllint 1.4.2 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
multi-cursor 2.1.5 
multi-paste 0.3.1 
open-recent 5.0.0 
platformio-ide-terminal 2.5.1 
print-atom 0.1.1 
prompt-big-file 0.3.0 
read-only-indicator 0.7.0 
readonly 0.2.0 
sensible-tab 1.0.0 
simple-align 0.2.0 
sort-lines 0.14.0 
split-diff 1.4.0 
status-bar-blame 1.0.5 
sync-settings 0.8.1 
tabs-to-spaces 1.0.3 
todo-show 1.11.0 
tree-view-open-files 0.3.0 
wordcount 2.10.4 
```

**Comment by eksortso** [comment]
Closing this. No longer using Atom, so it's moot.
